# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wrk',
            new_name='Todo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='wrk_lst',
            new_name='work_list',
        ),
    ]
