# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20160407_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='work_list',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
