# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20160408_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='work_list',
            new_name='task',
        ),
    ]
